### PR TITLE
add a new sentences file containing lines from screenplays

### PR DESCRIPTION
**Pull request by mikehenrty**

### CODE REVIEW

**Comment by davidflanagan** [comment]
This may well have changed since I worked on Murmur, but the tag associated with each sentence (the property name in this case) is used as a directory name in the local filesystem. The UUIDs (or hashes, maybe) include the / character in some of them, which seems likely to cause problems.  (Though like I said, maybe there is a different kind of data storage backend now and it isn't an issue.)

Also, there might be problems with some of the sentences. Scanning, I see these:

 - "Jus' like I'd tell you." - there may be an accessibility issue with dialect like this for non-American english speakers.   (I suppose, though that having samples of dialect would be good, but maybe better to get samples of "Jus'" by asking speakers of the dialect to say "Just" rather than asking non-speakers to fake it.)

- "situation) The police aren't going to like this one bit." - I think your sentence detection algorithm gets confused by parentheticals... I saw a couple of these unbalanced parens issues.

- "Les effets de Lampert." - not english!

You can fix some of these problems by filtering sentences so that any that contain words that are not in the dictionary get rejected.

The existing sentences.txt sentences had similar problems when Kelly generated them from Wikipedia. I wrote a script to clean them up and filter them before I gave them to Valerie to record. I probably still have the script. Let me know if you'd like it.

**Comment by mikehenrty** [comment]
Thanks for the review @davidflanagan !

Ok, I updated my parser to get rid of the "situation)" lines, and the colloquial "Jus' saying lines, and the French that we know about.
https://github.com/mikehenrty/screenplay2sentences/blob/a4da554663660edb071163802eb332013f70cbef/extract-lines.js#L82

I didn't write a full dictionary lookup, but I would love to see your script for cleaning up the lines we gave to Valerie.

As for the hash keys, that was specifically asked for by Andre, so I leave that up to him to tell me to change it :)

**Comment by andrenatal** [comment]
@mikehenrty: @davidflanagan is right, better keep the current pattern to the keys (sequential integers starting with 's', eg. s0001,s0002,s0003,...) please. 

BTW, it wasn't me who suggested SHA-1 hashes as keys.

**Comment by mbebenita** [comment]
Please leave in some identifier of paragraph structure, maybe group them by paragraph. Why have keys in the file at all? We could always just generate them as needed.

Sequential integers are probably hard to deal with in the future, if we remove or add new sentences.

**Comment by kdavis-mozilla** [comment]
@andrenatal Why can't you simply generate a UUID that can be a valid directory name?

Like @mbebenita I think keeping a sequential int across many generations of many apps and many sentences is just asking for a problem.

**Comment by mikehenrty** [comment]
Alright, I removed the IDs and just gave us a flat text file. I also grouped together paragraphs of dialog. There are still examples of single sentences, and examples of a couple sentence paragraphs. With the data we have now, I think we can test the usability of both the single sentence (shorter reward cycle) vs paragraph reading.

**Pull request merged**
